builds:
  - id: localize
    main: ./cmd/localize/main.go
    binary: localize
    goos:
      - linux
archives:
- replacements:
    linux: Linux
    386: i386
    amd64: x86_64
  files:
    - LICENSE
    - NOTICE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: netauth
    name: localizer
